name: app_proyect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.4
  permission_handler: ^11.3.0
  provider: ^6.1.2
  percent_indicator: ^4.2.2
  syncfusion_flutter_gauges: ^24.2.8
  fl_chart: ^1.0.0
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  


dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/esp32_wroom_32e.webp